### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [wallymathieu/Cake.SemVer.FromAssembly#2]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by wallymathieu** [comment]
There is XML documentation in the nuget package. The structure of the nuget is very much based on Cake.Gem in cake-contrib. I've added a pull request:
https://github.com/cake-build/website/pull/186

**Comment by gep13** [comment]
@wallymathieu thank you! This is now live on the site: http://cakebuild.net/addins/category/versioning

**Comment by wallymathieu** [comment]
Cool!
